From node:12

# 앱 디렉토리 생성
WORKDIR /usr/src/app

COPY package*.json /usr/src/app/
RUN npm install
RUN npm install -g pm2
COPY . /usr/src/app/

RUN npm run build

EXPOSE 3000

CMD ["pm2-runtime", "start", "dist/main.js", "-i", "max", "--output", "/home/contents/log/main_out.log"]